- name: Playbook for ActiveMQ Artemis
  hosts: all
  #become: true
  vars:
    # Setting this for unarchive to work
    ansible_remote_tmp: /home/makhlu
    # Описакнние параметров
    # https://github.com/ansible-middleware/amq/tree/main/roles/activemq   
    activemq_jvm_package: openjdk-19-jdk
    activemq_instance_username: ecm_adapter_admin # Username for accessing the broker instance
    activemq_instance_password: QEY73J7gCIh6cY1 # Password for accessing the broker instance
    activemq_queues:  ecm_general.in,ecm_general.out,ecm_commission.in,ecm_commission.out    # Queue names comma separated
    activemq_addresses:                # Addresses/queue configuration; list of { name, [anycast or multicast], and parameters }
    - name: ExpiryQueue
    anycast:
      - name: ExpiryQueue
      - name: Virtual
        anycast:
          - name: Virtual
            filter: "discard='true'"
            max_consumers: 5
            consumers_before_dispatch: 1    
    activemq_address_settings:          # Address settings configuration; list of { match address string and parameters(dict) }
      - match: activemq.management#
        parameters:
          dead_letter_address: DLQ
          expiry_address: ExpiryQueue
          redelivery_delay: 0
          max_size_bytes: -1
          message_counter_history_day_limit: 10
          address_full_policy: PAGE
          auto_create_queues: true
          auto_create_addresses: true
          auto_create_jms_queues: true
          auto_create_jms_topics: true  
  tasks:
  - name: Update and upgrade apt packages  
    become: true
    ansible.builtin.apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day               
  roles:
   - middleware_automation.amq.activemq      


    
