---
- name: Prepare
  hosts: all
  tasks:
    - name: "Run preparation common to all scenario"
      ansible.builtin.include_tasks: ../prepare.yml
      vars:
        assets:
          - "{{ assets_server }}/amq/broker/7.9.4/amq-broker-7.9.4-bin.zip"
    - name: "Create {{ activemq.service_name }} service user"
      become: yes
      ansible.builtin.user:
        name: amq-broker
        home: /opt/amq/
        system: yes
        create_home: no
    - name: Set ownership on nfs mounted parent
      file:
        path: /opt/amq/amq-broker/
        owner: amq-broker
        group: amq-broker
        mode: 0755