---
- name: Set journal configuration
  middleware_automation.amq.xml:
    path: "{{ activemq.instance_home }}/etc/broker.xml"
    xpath: "/conf:configuration/core:core/core:{{ item | replace('_','-') }}"
    value: "{{ lookup('ansible.builtin.vars', 'activemq_' + item) | to_json | replace('\"','') }}"
    namespaces:
      conf: urn:activemq
      core: urn:activemq:core
    pretty_print: yes
  become: yes
  notify:
    - restart amq_broker
  loop:
    - persistence_enabled
    - persist_id_cache
    - id_cache_size
    - journal_type
    - paging_directory
    - bindings_directory
    - journal_directory
    - large_messages_directory
    - journal_datasync
    - journal_min_files
    - journal_pool_files
    - journal_device_block_size
    - journal_file_size
    - journal_buffer_timeout
    - journal_max_io
    - configuration_file_refresh_period
  loop_control:
    label: "{{ item }}"
