---
- name: Converge
  hosts: all
  gather_facts: yes
  vars:
    activemq_hawtio_role: admin
    activemq_users:
      - user: amq
        password: amqbrokerpass
        roles: [ admin ]
      - user: other
        password: amqotherpass
        roles: [ consumer, producer ]
    activemq_roles:
      - name: admin
        permissions: [ createNonDurableQueue, deleteNonDurableQueue, createDurableQueue, deleteDurableQueue, createAddress, deleteAddress, consume, browse, send, manage ]
      - name: consumer
        match: topics.#
        permissions: [ consume, browse ]
      - name: producer
        match: topics.#
        permissions: [ send, browse ]
    activemq_acceptors:
      - name: artemis
        bind_address: "{{ activemq_host }}"
        bind_port: "{{ activemq_port }}"
        parameters:
          tcpSendBufferSize: 1048576
          tcpReceiveBufferSize: 1048576
          protocols: CORE,MQTT
          useEpoll: true
      - name: amqp
        bind_address: "{{ activemq_host }}"
        bind_port: "{{ activemq_port_amqp }}"
        parameters:
          tcpSendBufferSize: 1048576
          tcpReceiveBufferSize: 1048576
          protocols: AMQP
          useEpoll: true
          amqpMinLargeMessageSize: 102400
          amqpCredits: 1000
          amqpLowCredits: 300
          amqpDuplicateDetection: true
    activemq_diverts:
      - name: TESTDIVERT
        address: queue.in
        forwarding_address: queue.out
        routing_type: ANYCAST
        filter: "msgType LIKE '%ff%'"
        exclusive: True
  collections:
    - middleware_automation.common
  roles:
    - activemq
