---
    - name: Gather the package facts
      #become: true
      ansible.builtin.package_facts:  
        manager: auto

    - name: "Test if package not installed"
      ansible.builtin.debug:
         msg: "Package {{ item }} is not installed"
      loop: "{{ packages_list |difference( ansible_facts.packages.keys())  }}"

    - name: Update and upgrade apt packages before package install  
      become: true
      ansible.builtin.apt:
      #  upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day   
      when:  packages_list |difference( ansible_facts.packages.keys())  | length > 0  


    - name: "Install missing packages"
      become: yes        
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages_list |difference( ansible_facts.packages.keys())  }}"
      

       