---
- name: Validate parameters
  ansible.builtin.assert:
    that:
      - activemq.home is defined
      - activemq_service_user is defined
      - activemq_dest is defined
      - activemq.bundle is defined
      - activemq.download_url is defined
      - activemq.version is defined
    quiet: true

- name: "Create {{ activemq.service_name }} service group"
  become: yes
  ansible.builtin.group:
    name: "{{ activemq_service_group }}"
    system: yes

- name: "Create {{ activemq.service_name }} service user"
  become: yes
  ansible.builtin.user:
    name: "{{ activemq_service_user }}"
    group: "{{ activemq_service_group }}"
    home: "{{ activemq.home }}"
    system: yes
    create_home: no

- name: "Check {{ activemq.service_name }} install location"
  become: yes
  ansible.builtin.stat:
    path: "{{ activemq_dest }}"
  register: install_location

- name: "Create {{ activemq.service_name }} install location"
  become: yes
  ansible.builtin.file:
    dest: "{{ activemq_dest }}"
    state: directory
    owner: "{{ activemq_service_user }}"
    group: "{{ activemq_service_group }}"
    mode: 0750
  when:
    - not install_location.stat.exists

## check remote archive
- name: Set download archive path
  ansible.builtin.set_fact:
    archive: "{{ activemq_dest }}/{{ activemq.bundle }}"

- name: Check download archive path
  become: yes
  ansible.builtin.stat:
    path: "{{ archive }}"
  register: archive_path

## download to controller
- name: Download activemq archive
  ansible.builtin.get_url: # noqa risky-file-permissions delegated, uses controller host user
    url: "{{ activemq.download_url }}"
    dest: "{{ local_path.stat.path }}/{{ activemq.bundle }}"
    mode: 0640
  delegate_to: localhost
  run_once: yes
  when:
    - archive_path is defined
    - archive_path.stat is defined
    - not archive_path.stat.exists
    - not amq_broker_enable is defined or not amq_broker_enable
    - not activemq_offline_install

- name: Download AMQ broker from RHN using JBoss Network API
  delegate_to: localhost
  run_once: yes
  when:
    - archive_path is defined
    - archive_path.stat is defined
    - not archive_path.stat.exists
    - amq_broker_enable is defined and amq_broker_enable
    - not activemq_offline_install
    - rhn_username is defined and rhn_password is defined
  block:
    - name: Retrieve product download using JBoss Network API
      middleware_automation.common.product_search:
        client_id: "{{ rhn_username }}"
        client_secret: "{{ rhn_password }}"
        product_type: DISTRIBUTION
        product_version: "{{ amq_broker_version }}"
        product_category: "{{ amq_broker_product_category }}"
      register: rhn_products
      delegate_to: localhost
      run_once: yes

    - name: Determine install zipfile from search results
      ansible.builtin.set_fact:
        rhn_filtered_products: "{{ rhn_products.results | selectattr('file_path', 'match', '.*/amq-broker-' + amq_broker_version + '-bin.zip') }}"
      delegate_to: localhost
      run_once: yes

    - name: Download AMQ Broker
      middleware_automation.common.product_download:
        client_id: "{{ rhn_username }}"
        client_secret: "{{ rhn_password }}"
        product_id: "{{ (rhn_filtered_products | first).id }}"
        dest: "{{ local_path.stat.path }}/{{ activemq.bundle }}"
      no_log: "{{ omit_rhn_output | default(true) }}"
      delegate_to: localhost
      run_once: yes

- name: Check downloaded archive
  ansible.builtin.stat:
    path: "{{ local_path.stat.path }}/{{ activemq.bundle }}"
  register: local_archive_path
  delegate_to: localhost

## copy and unpack
- name: Copy archive to target nodes
  ansible.builtin.copy:
    src: "{{ local_path.stat.path }}/{{ activemq.bundle }}"
    dest: "{{ archive }}"
    owner: "{{ activemq_service_user }}"
    group: "{{ activemq_service_group }}"
    mode: 0750
  register: new_version_downloaded
  when:
    - not archive_path.stat.exists
    - local_archive_path.stat is defined
    - local_archive_path.stat.exists
  become: yes

- name: "Check target directory: {{ activemq.home }}"
  ansible.builtin.stat:
    path: "{{ activemq.home }}"
  register: path_to_workdir
  become: yes

- name: "Extract {{ activemq.name }} archive on target"
  ansible.builtin.unarchive: # noqa no-handler definitely not a candidate for a handler
    remote_src: yes
    src: "{{ archive }}"
    dest: "{{ activemq_dest }}"
    creates: "{{ activemq.home }}"
    owner: "{{ activemq_service_user }}"
    group: "{{ activemq_service_group }}"
  become: yes
  register: new_version_extracted
  when:
    - new_version_downloaded.changed or not path_to_workdir.stat.exists
  notify:
    - restart amq_broker

- name: Inform decompression was not executed
  ansible.builtin.debug: # noqa no-handler definitely not a candidate for a handler
    msg: "{{ activemq.home }} already exists and version unchanged, skipping decompression"
  when:
    - not new_version_downloaded.changed and path_to_workdir.stat.exists
